title: "Beetle and the wonderous world"
author: "Birdy Beetle"
description: "Nankeen night heron XD style=\"color: #f45;\">&lt;3</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: Floofy Birdy, icon: bird}
  - {file: "README.md", title: About Me, icon: snail}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:gooseygoosebeetle@gmail.com}
  - {title: Github, icon: github, url: "https://github.com/beethebeetle/beethebeetle"}
  - {title: Connect via the mycelium, icon: mushroom, url: "mushroomnewsletter@gmail.com"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
